package com.acuo.rules.marginrules

import com.acuo.common.model.margin.MarginCall
import com.acuo.common.model.agreements.Agreement
import com.acuo.common.model.margin.Types
import org.slf4j.Logger

global Logger log;

rule "threshold-secured"
    when
        $call: MarginCall($exposure:exposure)
        $agreement: Agreement(thresholdTreatment== "Secured",$exposure>threshold,agreementType in (Types.AgreementType.Regulatory_CSA,Types.AgreementType.CSA))
        $result: ThresholdResult();
    then
        $result.setExposure($exposure);
        $result.setAboveThreshold(true);
        update($result);
        log.info("Rule: '{}', threshold result: '{}'", drools.getRule().getName(), $result );
end

rule "threshold-unsecured"
    when
        $call: MarginCall($exposure:exposure)
        $agreement: Agreement(thresholdTreatment== "Unsecured",$exposure>threshold,$threshold:threshold, agreementType in (Types.AgreementType.Regulatory_CSA,Types.AgreementType.CSA))
        $result: ThresholdResult();
    then
        $result.setExposure($exposure - $threshold);
        $result.setAboveThreshold(true);
        update($result);
        log.info("Rule: '{}', threshold result: '{}'", drools.getRule().getName(), $result );
end