package com.acuo.rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Agreement implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String id;
   private java.util.List<java.lang.String> eligibleCurrency;
   private java.lang.String terminateCurrency;
   private java.lang.String marginType;

   private java.lang.String settlementCurrency;

   public Agreement()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.util.List<java.lang.String> getEligibleCurrency()
   {
      return this.eligibleCurrency;
   }

   public void setEligibleCurrency(
         java.util.List<java.lang.String> eligibleCurrency)
   {
      this.eligibleCurrency = eligibleCurrency;
   }

   public java.lang.String getTerminateCurrency()
   {
      return this.terminateCurrency;
   }

   public void setTerminateCurrency(java.lang.String terminateCurrency)
   {
      this.terminateCurrency = terminateCurrency;
   }

   public java.lang.String getMarginType()
   {
      return this.marginType;
   }

   public void setMarginType(java.lang.String marginType)
   {
      this.marginType = marginType;
   }

   public java.lang.String getSettlementCurrency()
   {
      return this.settlementCurrency;
   }

   public void setSettlementCurrency(java.lang.String settlementCurrency)
   {
      this.settlementCurrency = settlementCurrency;
   }

   public Agreement(java.lang.String id,
         java.util.List<java.lang.String> eligibleCurrency,
         java.lang.String terminateCurrency, java.lang.String marginType,
         java.lang.String settlementCurrency)
   {
      this.id = id;
      this.eligibleCurrency = eligibleCurrency;
      this.terminateCurrency = terminateCurrency;
      this.marginType = marginType;
      this.settlementCurrency = settlementCurrency;
   }

}