package com.acuo.rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Asset implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String type;
   private java.lang.String issuerCountry;
   private java.lang.String issuer;
   private java.lang.Boolean eligible;

   private java.lang.String eligibleType;

   private java.lang.String rating;

   private java.lang.Double maturityYears;

   private java.lang.Double haircut;

   private java.lang.Integer CQS;

   @javax.persistence.Id
   private java.lang.String id;

   private java.lang.Boolean issuerIsMemberState;

   private java.lang.Integer ratingScore;

   private java.lang.Boolean longTermRating;

   private java.lang.Boolean stanApproach;

   private java.lang.Boolean shortTermRating;

   private java.lang.Boolean IRBApproach;

   private java.lang.String entityLei;

   private java.lang.Boolean issuerIsMultiDevBank;

   private java.lang.String issuerOfficialName;

   private java.lang.Boolean issuerIsInterOrg;

   private java.lang.String datascopeAssetType;

   private java.lang.String creditPrincipalCode;

   private java.lang.String eeaClassType;

   private java.lang.String issuerCountryCode;

   private java.lang.String issuerDomCcy;

   private java.lang.String currency;

   private java.lang.String ultimateParentLei;

   private java.lang.Boolean convertibleFlag;

   private java.lang.String convertibleTypeCode;

   private java.lang.String convertInto;

   private java.lang.Boolean inMainIndex;

   private java.lang.Boolean inRecogExchange;

   private String mainIndex;

   private java.lang.Boolean inMainIdxAndRecExch;

   private java.lang.Double FXHaircut;

   private java.lang.String usClassType;

   private java.lang.String issuerOrgID;

   private boolean issuerIsUs6;

   private java.lang.Boolean issuerIsUSGovtAgency;

   private String exchange;

   public Asset()
   {
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public java.lang.String getIssuerCountry()
   {
      return this.issuerCountry;
   }

   public void setIssuerCountry(java.lang.String issuerCountry)
   {
      this.issuerCountry = issuerCountry;
   }

   public java.lang.String getIssuer()
   {
      return this.issuer;
   }

   public void setIssuer(java.lang.String issuer)
   {
      this.issuer = issuer;
   }

   public java.lang.Boolean getEligible()
   {
      return this.eligible;
   }

   public void setEligible(java.lang.Boolean eligible)
   {
      this.eligible = eligible;
   }

   public java.lang.String getEligibleType()
   {
      return this.eligibleType;
   }

   public void setEligibleType(java.lang.String eligibleType)
   {
      this.eligibleType = eligibleType;
   }

   public java.lang.String getRating()
   {
      return this.rating;
   }

   public void setRating(java.lang.String rating)
   {
      this.rating = rating;
   }

   public java.lang.Double getMaturityYears()
   {
      return this.maturityYears;
   }

   public void setMaturityYears(java.lang.Double maturityYears)
   {
      this.maturityYears = maturityYears;
   }

   public java.lang.Double getHaircut()
   {
      return this.haircut;
   }

   public void setHaircut(java.lang.Double haircut)
   {
      this.haircut = haircut;
   }

   public java.lang.Integer getCQS()
   {
      return this.CQS;
   }

   public void setCQS(java.lang.Integer CQS)
   {
      this.CQS = CQS;
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.Boolean getIssuerIsMemberState()
   {
      return this.issuerIsMemberState;
   }

   public void setIssuerIsMemberState(java.lang.Boolean issuerIsMemberState)
   {
      this.issuerIsMemberState = issuerIsMemberState;
   }

   public java.lang.Integer getRatingScore()
   {
      return this.ratingScore;
   }

   public void setRatingScore(java.lang.Integer ratingScore)
   {
      this.ratingScore = ratingScore;
   }

   public java.lang.Boolean getLongTermRating()
   {
      return this.longTermRating;
   }

   public void setLongTermRating(java.lang.Boolean longTermRating)
   {
      this.longTermRating = longTermRating;
   }

   public java.lang.Boolean getStanApproach()
   {
      return this.stanApproach;
   }

   public void setStanApproach(java.lang.Boolean stanApproach)
   {
      this.stanApproach = stanApproach;
   }

   public java.lang.Boolean getShortTermRating()
   {
      return this.shortTermRating;
   }

   public void setShortTermRating(java.lang.Boolean shortTermRating)
   {
      this.shortTermRating = shortTermRating;
   }

   public java.lang.Boolean getIRBApproach()
   {
      return this.IRBApproach;
   }

   public void setIRBApproach(java.lang.Boolean IRBApproach)
   {
      this.IRBApproach = IRBApproach;
   }

   public java.lang.String getEntityLei()
   {
      return this.entityLei;
   }

   public void setEntityLei(java.lang.String entityLei)
   {
      this.entityLei = entityLei;
   }

   public java.lang.Boolean getIssuerIsMultiDevBank()
   {
      return this.issuerIsMultiDevBank;
   }

   public void setIssuerIsMultiDevBank(java.lang.Boolean issuerIsMultiDevBank)
   {
      this.issuerIsMultiDevBank = issuerIsMultiDevBank;
   }

   public java.lang.String getIssuerOfficialName()
   {
      return this.issuerOfficialName;
   }

   public void setIssuerOfficialName(java.lang.String issuerOfficialName)
   {
      this.issuerOfficialName = issuerOfficialName;
   }

   public java.lang.Boolean getIssuerIsInterOrg()
   {
      return this.issuerIsInterOrg;
   }

   public void setIssuerIsInterOrg(java.lang.Boolean issuerIsInterOrg)
   {
      this.issuerIsInterOrg = issuerIsInterOrg;
   }

   public java.lang.String getDatascopeAssetType()
   {
      return this.datascopeAssetType;
   }

   public void setDatascopeAssetType(java.lang.String datascopeAssetType)
   {
      this.datascopeAssetType = datascopeAssetType;
   }

   public java.lang.String getCreditPrincipalCode()
   {
      return this.creditPrincipalCode;
   }

   public void setCreditPrincipalCode(java.lang.String creditPrincipalCode)
   {
      this.creditPrincipalCode = creditPrincipalCode;
   }

   public java.lang.String getEeaClassType()
   {
      return this.eeaClassType;
   }

   public void setEeaClassType(java.lang.String eeaClassType)
   {
      this.eeaClassType = eeaClassType;
   }

   public java.lang.String getIssuerCountryCode()
   {
      return this.issuerCountryCode;
   }

   public void setIssuerCountryCode(java.lang.String issuerCountryCode)
   {
      this.issuerCountryCode = issuerCountryCode;
   }

   public java.lang.String getIssuerDomCcy()
   {
      return this.issuerDomCcy;
   }

   public void setIssuerDomCcy(java.lang.String issuerDomCcy)
   {
      this.issuerDomCcy = issuerDomCcy;
   }

   public java.lang.String getCurrency()
   {
      return this.currency;
   }

   public void setCurrency(java.lang.String currency)
   {
      this.currency = currency;
   }

   public java.lang.String getUltimateParentLei()
   {
      return this.ultimateParentLei;
   }

   public void setUltimateParentLei(java.lang.String ultimateParentLei)
   {
      this.ultimateParentLei = ultimateParentLei;
   }

   public java.lang.Boolean getConvertibleFlag()
   {
      return this.convertibleFlag;
   }

   public void setConvertibleFlag(java.lang.Boolean convertibleFlag)
   {
      this.convertibleFlag = convertibleFlag;
   }

   public java.lang.String getConvertibleTypeCode()
   {
      return this.convertibleTypeCode;
   }

   public void setConvertibleTypeCode(java.lang.String convertibleTypeCode)
   {
      this.convertibleTypeCode = convertibleTypeCode;
   }

   public java.lang.String getConvertInto()
   {
      return this.convertInto;
   }

   public void setConvertInto(java.lang.String convertInto)
   {
      this.convertInto = convertInto;
   }

   public java.lang.Boolean getInMainIndex()
   {
      return this.inMainIndex;
   }

   public void setInMainIndex(java.lang.Boolean inMainIndex)
   {
      this.inMainIndex = inMainIndex;
   }

   public java.lang.Boolean getInRecogExchange()
   {
      return this.inRecogExchange;
   }

   public void setInRecogExchange(java.lang.Boolean inRecogExchange)
   {
      this.inRecogExchange = inRecogExchange;
   }

   public java.lang.String getMainIndex()
   {
      return this.mainIndex;
   }

   public void setMainIndex(java.lang.String mainIndex)
   {
      this.mainIndex = mainIndex;
   }

   public java.lang.Boolean getInMainIdxAndRecExch()
   {
      return this.inMainIdxAndRecExch;
   }

   public void setInMainIdxAndRecExch(java.lang.Boolean inMainIdxAndRecExch)
   {
      this.inMainIdxAndRecExch = inMainIdxAndRecExch;
   }

   public java.lang.Double getFXHaircut()
   {
      return this.FXHaircut;
   }

   public void setFXHaircut(java.lang.Double FXHaircut)
   {
      this.FXHaircut = FXHaircut;
   }

   public java.lang.String getUsClassType()
   {
      return this.usClassType;
   }

   public void setUsClassType(java.lang.String usClassType)
   {
      this.usClassType = usClassType;
   }

   public java.lang.String getIssuerOrgID()
   {
      return this.issuerOrgID;
   }

   public void setIssuerOrgID(java.lang.String issuerOrgID)
   {
      this.issuerOrgID = issuerOrgID;
   }

   public boolean isIssuerIsUs6()
   {
      return this.issuerIsUs6;
   }

   public void setIssuerIsUs6(boolean issuerIsUs6)
   {
      this.issuerIsUs6 = issuerIsUs6;
   }

   public java.lang.Boolean getIssuerIsUSGovtAgency()
   {
      return this.issuerIsUSGovtAgency;
   }

   public void setIssuerIsUSGovtAgency(java.lang.Boolean issuerIsUSGovtAgency)
   {
      this.issuerIsUSGovtAgency = issuerIsUSGovtAgency;
   }

   public java.lang.String getExchange()
   {
      return this.exchange;
   }

   public void setExchange(java.lang.String exchange)
   {
      this.exchange = exchange;
   }

   public Asset(java.lang.String type, java.lang.String issuerCountry,
         java.lang.String issuer, java.lang.Boolean eligible,
         java.lang.String eligibleType, java.lang.String rating,
         java.lang.Double maturityYears, java.lang.Double haircut,
         java.lang.Integer CQS, java.lang.String id,
         java.lang.Boolean issuerIsMemberState, java.lang.Integer ratingScore,
         java.lang.Boolean longTermRating, java.lang.Boolean stanApproach,
         java.lang.Boolean shortTermRating, java.lang.Boolean IRBApproach,
         java.lang.String entityLei, java.lang.Boolean issuerIsMultiDevBank,
         java.lang.String issuerOfficialName,
         java.lang.Boolean issuerIsInterOrg,
         java.lang.String datascopeAssetType,
         java.lang.String creditPrincipalCode, java.lang.String eeaClassType,
         java.lang.String issuerCountryCode, java.lang.String issuerDomCcy,
         java.lang.String currency, java.lang.String ultimateParentLei,
         java.lang.Boolean convertibleFlag,
         java.lang.String convertibleTypeCode, java.lang.String convertInto,
         java.lang.Boolean inMainIndex, java.lang.Boolean inRecogExchange,
         java.lang.String mainIndex, java.lang.Boolean inMainIdxAndRecExch,
         java.lang.Double FXHaircut, java.lang.String usClassType,
         java.lang.String issuerOrgID, boolean issuerIsUs6,
         java.lang.Boolean issuerIsUSGovtAgency, java.lang.String exchange)
   {
      this.type = type;
      this.issuerCountry = issuerCountry;
      this.issuer = issuer;
      this.eligible = eligible;
      this.eligibleType = eligibleType;
      this.rating = rating;
      this.maturityYears = maturityYears;
      this.haircut = haircut;
      this.CQS = CQS;
      this.id = id;
      this.issuerIsMemberState = issuerIsMemberState;
      this.ratingScore = ratingScore;
      this.longTermRating = longTermRating;
      this.stanApproach = stanApproach;
      this.shortTermRating = shortTermRating;
      this.IRBApproach = IRBApproach;
      this.entityLei = entityLei;
      this.issuerIsMultiDevBank = issuerIsMultiDevBank;
      this.issuerOfficialName = issuerOfficialName;
      this.issuerIsInterOrg = issuerIsInterOrg;
      this.datascopeAssetType = datascopeAssetType;
      this.creditPrincipalCode = creditPrincipalCode;
      this.eeaClassType = eeaClassType;
      this.issuerCountryCode = issuerCountryCode;
      this.issuerDomCcy = issuerDomCcy;
      this.currency = currency;
      this.ultimateParentLei = ultimateParentLei;
      this.convertibleFlag = convertibleFlag;
      this.convertibleTypeCode = convertibleTypeCode;
      this.convertInto = convertInto;
      this.inMainIndex = inMainIndex;
      this.inRecogExchange = inRecogExchange;
      this.mainIndex = mainIndex;
      this.inMainIdxAndRecExch = inMainIdxAndRecExch;
      this.FXHaircut = FXHaircut;
      this.usClassType = usClassType;
      this.issuerOrgID = issuerOrgID;
      this.issuerIsUs6 = issuerIsUs6;
      this.issuerIsUSGovtAgency = issuerIsUSGovtAgency;
      this.exchange = exchange;
   }

}