package com.acuo.rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Exchange implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.Id
   private java.lang.String MIC;
   private java.lang.String name;

   public Exchange()
   {
   }

   public java.lang.String getMIC()
   {
      return this.MIC;
   }

   public void setMIC(java.lang.String MIC)
   {
      this.MIC = MIC;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public Exchange(java.lang.String MIC, java.lang.String name)
   {
      this.MIC = MIC;
      this.name = name;
   }

}