package com.acuo.rules.assets

import org.slf4j.Logger
import com.acuo.common.model.assets.*
global Logger log;

rule "Exists"
    when
         $assets: Assets( type in ("cash","equity"), $id:assetId )
        $exist: Exist()
        //eval($assets.getAssetId()=="a1")
        eval($id=="a1")

    then
            log.info(
                "Rule: '{}'",
                drools.getRule().getName()
            );
        System.out.println("Assets exists");
        $exist.setDoesExist(true);
end