package com.acuo.rules.eligibility

import org.slf4j.Logger
import com.acuo.common.model.assets.*
import com.acuo.common.model.agreements.*

global Logger log;

rule "cash is eligible for VM"
    when
        $asset: Assets(type == "cash")
        $agreement: Agreement( id=="ag1")
        $eligible: Eligible()
    then
        log.info(
            "Rule: '{}', asset: '{}', agreement '{}'",
            drools.getRule().getName(),
            $asset,
            $agreement
        );

        $eligible.setIsEligible(true);
        update($eligible);
end