package com.acuo.rules.eligibility

import org.slf4j.Logger

global Logger log;

rule "rule-moody-haircut-cmpt"
	when
		$provider:HaircutProvider(name=="Moody")
		$eligible:EligibleResult($vp: valuationPercentage!=-1)
	then
		$eligible.setIsEligible(true);
		$eligible.setFxHaircut(0);
		$eligible.setHaircut(1- $vp);
		update($eligible);
        log.info("Rule: '{}'", drools.getRule().getName());

end