package com.acuo.rules.eligibility

import org.slf4j.Logger

global Logger log;

rule "rule-fitch-haircut-cmpt"
//agenda-group "FitchHaircut"
//salience -10
	when
		$provider:HaircutProvider(name=="Fitch")
		$eligible:Eligible($secAR: securityAR!=-1, $fxAR: FXAR!=-1)
	then
		$eligible.setIsEligible(true);
		$eligible.setFxHaircut(0);
		$eligible.setValuationPercentage($secAR * $fxAR);
		$eligible.setHaircut(1- $secAR * $fxAR);
		update($eligible);
        log.info("Rule: '{}'", drools.getRule().getName() );
end