package com.acuo.rules.eligibility

import com.acuo.common.model.assets.Assets
import com.acuo.common.model.agreements.Agreement
import com.acuo.common.model.margin.Types
import org.slf4j.Logger
global Logger log;

rule "ctpyApplyWithCollateralFlipClause"
	when
		$counterpart : Counterpart(countryCode in ("AU","BE","BG","HR","CY",
                                  "CZ","DK","EE","FI","FR",
                                  "DE","GR","HU","IE","IT",
                                  "LV","LT","LU","MT","NL",
                                  "PL","PT","RO","SK","SI",
                                  "ES","SE","GB","UK"));
	then
		$counterpart.setWithCollateralFlipClause( true );
		update($counterpart);
        log.info("Rule: '{}'", drools.getRule().getName());
end
