package com.acuo.rules.eligibility

import org.slf4j.Logger
import com.acuo.common.model.assets.*
import java.lang.Number

global Logger log;

rule "eea-FXHaircut-vm-a"
	when
		$asset: LocalAsset(type!= "cash")
		$ag: LocalAgreement(marginType == "Variation", eligibleCurrency != $asset.currency)
		$provider: HaircutProvider(name == "EEA")
		$eligible: Eligible()
	then
		$eligible.setFxHaircut( 0.08 );
		update($eligible);
		System.out.println("fire eea-FXHaircut-vm-a");
end

