package com.acuo.rules.eligibility

import org.slf4j.Logger
import com.acuo.common.model.assets.*

global Logger log;

rule "rule-eea-class-a"
	when
		$asset : Assets( type == "cash" )
		$eligible: Eligible()
		$regime: Regime(name == "EEA")

	then
	log.info(
                "Rule: '{}', asset: '{}'",
                drools.getRule().getName(),
                $asset
            );

		$eligible.setClassType( "EEAa" );
		update($eligible)
end

rule "rule-eea-eli-a"
	when
		$asset : Assets( )
		$eligible: Eligible(classType == "EEAa")
	then
		$eligible.setIsEligible( true );
		update($eligible)
end
