package com.acuo.rules.eligibility

import org.slf4j.Logger

global Logger log;

rule "rule-eea-class-h"

	when
		$asset : LocalAsset(type == "bond" )
		$issuer: Issuer(isMultiDevBank == true)
		$provider: HaircutProvider(name == "EEA")
		$eligible: Eligible()
	then
		$eligible.setClassType( "EEAh" );
		update($eligible)
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-eli-h"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "EEAh")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end
