package com.acuo.rules.eligibility

import org.slf4j.Logger
import com.acuo.common.model.assets.*
import java.lang.Number

global Logger log;

rule "eea-FXHaircut-vm-cash"
	when
		$asset: LocalAsset(type== "cash")
		$ag: LocalAgreement(marginType == "Variation")
		$provider: HaircutProvider(name == "EEA")
		$eligible: Eligible()
	then
		$eligible.setFxHaircut( 0 );
		update($eligible);
		System.out.println("fire eea-FXHaircut-vm-cash");
end

