package com.acuo.rules.eligibility

import org.slf4j.Logger
import com.acuo.common.model.assets.*

global Logger log;

rule "rule-eea-class-q"
	when
		$asset : LocalAsset(type == "equity")
		$regime: Regime(name == "EEA",ineeaMainIndex($asset.index), ineeaexchange($asset.exchange))
		$eligible: Eligible()


	then
	log.info(
                "Rule: '{}', asset: '{}'",
                drools.getRule().getName(),
                $asset
            );

		$eligible.setClassType( "EEAq" );
		update($eligible)
end

rule "rule-eea-eli-q"
	when
		$asset : LocalAsset()
		$eligible: Eligible(classType == "EEAq")
		$c: Client()
		$issuer: Issuer(entityLei != $c.entityLei && ultimateParentLei != $c.ultimateParentLei )
	then
		$eligible.setIsEligible( true );
		update($eligible)
end
