package com.acuo.rules.eligibility

import org.slf4j.Logger

global Logger log;

rule "rule-eea-class-a"
	when
		$asset : LocalAsset( type == "cash" )
		$eligible: Eligible()
		$provider: HaircutProvider(name == "EEA")

	then
		$eligible.setClassType( "EEAa" );
		update($eligible)
		log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );

end

rule "rule-eea-eli-a"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "EEAa")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-class-b"
	when
		$asset : LocalAsset( type == "gold" )
		$eligible: Eligible()
		$provider: HaircutProvider(name == "EEA")

	then
        $eligible.setClassType( "EEAb" );
        update($eligible)
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );

end

rule "rule-eea-eli-b"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "EEAb")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-class-c"

	when
		$asset : LocalAsset(type == "bond" , datascopeAssetType == "GOVT")

		$issuer: Issuer(isMemberState == true)
		$provider: HaircutProvider(name == "EEA")
		$eligible: Eligible()
	then

		$eligible.setClassType( "EEAc" );
		update($eligible)
		log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-eli-c"
	when
		$issuer: Issuer()
		$eligible: Eligible(classType == "EEAc")
		$asset : LocalAsset( (currency!=$issuer.domCurrency) || ((currency==$issuer.domCurrency) && CQS in ( 1, 2, 3, 4 )) )
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-class-h"

	when
		$asset : LocalAsset(type == "bond" )
		$issuer: Issuer(isMultiDevBank == true)
		$provider: HaircutProvider(name == "EEA")
		$eligible: Eligible()
	then
		$eligible.setClassType( "EEAh" );
		update($eligible)
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-eli-h"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "EEAh")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-class-i"
	when
		$asset : LocalAsset( type == "bond" )
		$issuer : Issuer(isInterOrg==true)
		$eligible: Eligible()
		$provider: HaircutProvider(name == "EEA")

	then

		$eligible.setClassType( "EEAi" );
		update($eligible)
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-eli-i"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "EEAi")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-class-j"
	when
		$asset : LocalAsset( type == "bond", datascopeAssetType == "GOVT" )
		$eligible: Eligible()
		$issuer: Issuer(isMemberState == false)
		$provider: HaircutProvider(name == "EEA")

	then

		$eligible.setClassType( "EEAj" );
		update($eligible)
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-eli-j"
	when
		$asset : LocalAsset(CQS in ( 1, 2, 3 ))
		$eligible: Eligible(classType == "EEAj")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-class-n"
	when
		$asset : LocalAsset( type == "bond", datascopeAssetType == "CORP" )
		$eligible: Eligible()
		$provider: HaircutProvider(name == "EEA")

	then
		$eligible.setClassType( "EEAn" );
		update($eligible)
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-eli-n"
	when
	    $c : Client()
	    $asset: LocalAsset()
		$issuer : Issuer(entityLei != $c.entityLei && ultimateParentLei != $c.ultimateParentLei && $asset.CQS in ( 1, 2, 3 )  )
		$eligible: Eligible(classType == "EEAn")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-class-o"
	when
		$asset : LocalAsset( type == "bond", creditPrincipalCode == "SR" )
		$eligible: Eligible()
		$provider: HaircutProvider(name == "EEA")

	then

		$eligible.setClassType( "EEAo" );
		update($eligible)
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-eli-o"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "EEAo")
		$c: Client()
		$issuer: Issuer( entityLei != $c.entityLei && ultimateParentLei != $c.ultimateParentLei && $asset.CQS in ( 1, 2, 3 ))
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-class-p"
when
    $asset : LocalAsset( type == "bond" && convertibleFlag == true && convertibleTypeCode == "EI")
    $eligible: Eligible()
    $provider: HaircutProvider(name == "EEA", ineeaMainIndex($asset.index), ineeaexchange($asset.exchange))

then

    $eligible.setClassType( "EEAp" );
    update($eligible)
    log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end


rule "rule-eea-eli-p"
when
    $asset : LocalAsset()
    $eligible: Eligible(classType == "EEAp")
then
    $eligible.setIsEligible( true );
    update($eligible);
    log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end


rule "rule-eea-class-q"
	when
		$asset : LocalAsset(type == "equity")
		$provider: HaircutProvider(name =="EEA",ineeaMainIndex($asset.index), ineeaexchange($asset.exchange))
		$eligible: Eligible()


	then
		$eligible.setClassType( "EEAq" );
		update($eligible)
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-eli-q"
	when
		$asset : LocalAsset()
		$eligible: Eligible(classType == "EEAq")
		$c: Client()
		$issuer: Issuer(entityLei != $c.entityLei && ultimateParentLei != $c.ultimateParentLei )
	then
		$eligible.setIsEligible( true );
		$eligible.setHaircut(0.15);
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end



