package com.acuo.rules.eligibility

import org.slf4j.Logger
import com.acuo.common.model.assets.*
import java.lang.Number

global Logger log;

rule "eea-FXHaircut-im"
	when
		$ag: LocalAgreement(marginType == "Initial")
		$asset: LocalAsset(currency == $ag.terminateCurrency)
		$eligible: Eligible()

		$provider: HaircutProvider(name == "EEA")
	then
		$eligible.setFxHaircut( 0 );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

