package com.acuo.rules.eligibility

import org.slf4j.Logger
import com.acuo.common.model.assets.*

global Logger log;

rule "rule-eea-class-b"
	when
		$asset : LocalAsset( type == "gold" )
		$eligible: Eligible()
		$provider: HaircutProvider(name == "EEA")

	then
        $eligible.setClassType( "EEAb" );
        update($eligible)
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );

end

rule "rule-eea-eli-b"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "EEAb")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end
