package com.acuo.rules.eligibility

import org.slf4j.Logger

global Logger log;

rule "rule-eea-class-i"
	when
		$asset : LocalAsset( type == "bond" )
		$issuer : Issuer(isInterOrg==true)
		$eligible: Eligible()
		$provider: HaircutProvider(name == "EEA")

	then

		$eligible.setClassType( "EEAi" );
		update($eligible)
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-eli-i"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "EEAi")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end
