package com.acuo.rules.eligibility

import org.slf4j.Logger
import com.acuo.common.model.assets.*

global Logger log;

rule "rule-eea-class-n"
	when
		$asset : LocalAsset( type == "bond", datascopeAssetType == "CORP" )
		$eligible: Eligible()
		$provider: HaircutProvider(name == "EEA")

	then
	log.info(
                "Rule: '{}', asset: '{}'",
                drools.getRule().getName(),
                $asset
            );

		$eligible.setClassType( "EEAn" );
		update($eligible)
end

rule "rule-eea-eli-n"
	when
	    $c : Client()
	    $asset: LocalAsset()
		$issuer : Issuer(entityLei != $c.entityLei && ultimateParentLei != $c.ultimateParentLei && $asset.CQS in ( 1, 2, 3 )  )
		$eligible: Eligible(classType == "EEAn")
	then
		$eligible.setIsEligible( true );
		update($eligible);
		System.out.println("fire rule-eea-eli-n");
end
