package com.acuo.rules.eligibility

import org.slf4j.Logger
import com.acuo.common.model.assets.*

global Logger log;

rule "rule-eea-class-q"
	when
		$asset : LocalAsset(type == "equity")
		$provider: HaircutProvider(name =="EEA",ineeaMainIndex($asset.index), ineeaexchange($asset.exchange))
		$eligible: Eligible()


	then
		$eligible.setClassType( "EEAq" );
		update($eligible)
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-eli-q"
	when
		$asset : LocalAsset()
		$eligible: Eligible(classType == "EEAq")
		$c: Client()
		$issuer: Issuer(entityLei != $c.entityLei && ultimateParentLei != $c.ultimateParentLei )
	then
		$eligible.setIsEligible( true );
		$eligible.setHaircut(0.15);
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end
