package com.acuo.rules.eligibility

import org.slf4j.Logger
import com.acuo.common.model.assets.*

global Logger log;

rule "rule-eea-class-h"

	when
		$asset : LocalAsset(type == "bond" )
		$issuer: Issuer(isMultiDevBank == true)
		$regime: Regime(name == "EEA")
		$eligible: Eligible()
	then
		log.info(
                    "Rule: '{}', asset: '{}', issuer:'{}'",
                    drools.getRule().getName(),
                    $asset,
                    $issuer
                );
		$eligible.setClassType( "EEAh" );
		update($eligible)
end

rule "rule-eea-eli-h"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "EEAh")
	then
		$eligible.setIsEligible( true );
		update($eligible)
end
