package com.acuo.rules.eligibility

import org.slf4j.Logger
import com.acuo.common.model.assets.*

global Logger log;

rule "rule-eea-class-o"
	when
		$asset : LocalAsset( type == "bond", creditPrincipalCode == "SR" )
		$eligible: Eligible()
		$regime: Regime(name == "EEA")

	then
	log.info(
                "Rule: '{}', asset: '{}'",
                drools.getRule().getName(),
                $asset
            );

		$eligible.setClassType( "EEAo" );
		update($eligible)
end

rule "rule-eea-eli-o"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "EEAo")
		$c: Client()
		$issuer: Issuer( entityLei != $c.entityLei && ultimateParentLei != $c.ultimateParentLei && $asset.CQS in ( 1, 2, 3 ))
	then
		$eligible.setIsEligible( true );
		update($eligible)
end
