package com.acuo.rules.eligibility

import org.slf4j.Logger
import com.acuo.common.model.assets.*

global Logger log;

rule "rule-eea-class-j"
	when
		$asset : LocalAsset( type == "bond", datascopeAssetType == "GOVT" )
		$eligible: Eligible()
		$issuer: Issuer(isMemberState == false)
		$provider: HaircutProvider(name == "EEA")

	then
	log.info(
                "Rule: '{}', asset: '{}'",
                drools.getRule().getName(),
                $asset
            );

		$eligible.setClassType( "EEAj" );
		update($eligible)
end

rule "rule-eea-eli-j"
	when
		$asset : LocalAsset(CQS in ( 1, 2, 3 ))
		$eligible: Eligible(classType == "EEAj")
	then
		$eligible.setIsEligible( true );
		update($eligible);
		System.out.println("fire rule-eea-eli-j");
end
