package com.acuo.rules.eligibility

import org.slf4j.Logger

import com.acuo.common.model.assets.Assets
import com.acuo.common.model.agreements.Agreement

import java.util.List;
import java.util.ArrayList;
import java.io.*;
import java.util.*;

global Logger log;

function boolean ineeaMainIndex(String index)
{
    String e[]=index.split(",");

    String bench[]={"S&P 500",
                    "NASDAQ100",
                    "STOXX Asia/Pacific 600",
                    "ASX100",
                    "ATX Prime",
                    "BEL20",
                    "IBOVESPA",
                    "TSX60",
                    "CETOP20 Index",
                    "Hang Seng Mainland 100 Index (China)",
                    "NYSE ARCA China Index",
                    "Shanghai Shenzhen CSI 300",
                    "PX Prague",
                    "OMX Copenhagen 20",
                    "FTSE RAFI Emerging Markets",
                    "MSCI Emerging Markets 50",
                    "FTSE Europe Index",
                    "STOXX Europe 600",
                    "MSCI AC Europe & Middle East",
                    "OMXH25",
                    "SBF120",
                    "S&P BMI France",
                    "HDAX",
                    "FTSE All World Index",
                    "MSCI ACWI",
                    "FT ASE Large Cap",
                    "Hang Seng",
                    "CNX 100 Index",
                    "S&P BSE 100 Index",
                    "ISEQ 20",
                    "FTSE MIB",
                    "Nikkei 300",
                    "TOPIX mid 400",
                    "S&P Latin America 40",
                    "FTSE Bursa Malaysia KLCI Index",
                    "Mexico Bolsa Index",
                    "AEX",
                    "S&P NZX 15 Index",
                    "OBX" ,
                    "WIG20",
                    "PSI 20",
                    "MSCI Russia Index",
                    "Russian Traded Index",
                    "FTSE Straits Times Index",
                    "FTSE JSE Top 40",
                    "INDI 25 Index",
                    'KOSPI 100',
                    "IBEX35",
                    "OMXS60",
                    "OMXSB",
                    "SMI Expanded Index",
                    "TSEC Taiwan 50",
                    "FTSE Nasdaq Dubai UAE 20 Index",
                    "FTSE 350"};
    int flag = 0;
    for(int i = 0; i < e.length; i++)
    {
    //System.out.println(flag);
    //System.out.println("_____________");
    //System.out.println("e:" + e[i]);
        for(int j = 0; j < bench.length; j++)
        {
         //System.out.println("bench"+j+":" + bench[j] +"  " + "e"+i +":"+ e[i]+ "   " + "Judge:"+(bench[j].equals(e[i])));
	     if (bench[j].equals(e[i]))
         {
		  flag = 1;
		  break;
         }
        }
        if (flag==1)
         {
              break;

         }
    }

    //System.out.println(flag);
    if (flag==1)
        {
            return true;

        }
    else
        {
            return false;
        }

}

