package com.acuo.rules.eligibility

import org.slf4j.Logger

global Logger log;

rule "rule-eea-class-c"

	when
		$asset : LocalAsset(type == "bond" , datascopeAssetType == "GOVT")

		$issuer: Issuer(isMemberState == true)
		$provider: HaircutProvider(name == "EEA")
		$eligible: Eligible()
	then

		$eligible.setClassType( "EEAc" );
		update($eligible)
end

rule "rule-eea-eli-c"
	when
		$issuer: Issuer()
		$eligible: Eligible(classType == "EEAc")
		$asset : LocalAsset( (currency!=$issuer.domCurrency) || ((currency==$issuer.domCurrency) && CQS in ( 1, 2, 3, 4 )) )
	then
		$eligible.setIsEligible( true );
		update($eligible);
		System.out.println("fire rule-eea-eli-c");
end
