package com.acuo.rules.eligibility

import org.slf4j.Logger

global Logger log;

rule "rule-eea-class-a"
	when
		$asset : LocalAsset( type == "cash" )
		$eligible: Eligible()
		$provider: HaircutProvider(name == "EEA")

	then
	log.info(
                "Rule: '{}', asset: '{}'",
                drools.getRule().getName(),
                $asset
            );

		$eligible.setClassType( "EEAa" );
		update($eligible)
end

rule "rule-eea-eli-a"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "EEAa")
	then
		$eligible.setIsEligible( true );
		update($eligible);
		System.out.println("fire rule-eea-eli-a");

end
