package com.acuo.rules.eligibility

import com.acuo.common.model.assets.Assets
import com.acuo.common.model.agreements.Agreement
import com.acuo.common.model.margin.Types

import org.slf4j.Logger
global Logger log;

rule "rule-eea-class-a"
	when
		$asset : Assets( type == "cash" )
		$eligible: EligibleResult()
		$provider: HaircutProvider(name == "EEA")

	then
		$eligible.setClassType( "EEAa" );
		update($eligible)
		log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );

end

rule "rule-eea-eli-a"
	when
		$asset : Assets( )
		$eligible: EligibleResult(classType == "EEAa")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-class-b"
	when
		$asset : Assets( type == "gold" )
		$eligible: EligibleResult()
		$provider: HaircutProvider(name == "EEA")

	then
        $eligible.setClassType( "EEAb" );
        update($eligible)
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );

end

rule "rule-eea-eli-b"
	when
		$asset : Assets( )
		$eligible: EligibleResult(classType == "EEAb")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-class-c"
	when
		$asset : Assets(type == "bond" , assetType == "GOVT", issuerIsMemberState)
		$provider: HaircutProvider(name == "EEA")
		$eligible: EligibleResult()
	then
		$eligible.setClassType( "EEAc" );
		update($eligible)
		log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-eli-c"
	when
		$eligible: EligibleResult(classType == "EEAc")
		//$asset : Assets( (currency!=$issuer.domCurrency && $issuer.domCurrency!=null) || ((currency==$issuer.domCurrency) && CQS in ( 1, 2, 3, 4 )) )
		$asset : Assets( CQS in ( 1, 2, 3, 4 ))
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-class-hi"
	when
		$asset : Assets(type == "bond",issuerSector=="SPRA")
		//$issuer: Issuer(sector == "SPRA")
		$provider: HaircutProvider(name == "EEA")
		$eligible: EligibleResult()
	then
		$eligible.setClassType( "EEAhi" );
		update($eligible)
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-eli-hi"
	when
		$asset : Assets( )
		$eligible: EligibleResult(classType == "EEAhi")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-class-j"
	when
		$asset : Assets( type == "bond", assetType == "GOVT",!issuerIsMemberState )
		$eligible: EligibleResult()
		//$issuer: Issuer(isMemberState == false)
		$provider: HaircutProvider(name == "EEA")

	then

		$eligible.setClassType( "EEAj" );
		update($eligible)
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-eli-j"
	when
		$asset : Assets(CQS in ( 1, 2, 3 ))
		$eligible: EligibleResult(classType == "EEAj")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-class-n"
	when
		$asset : Assets( type == "bond", assetType == "CORP" )
		$eligible: EligibleResult()
		$provider: HaircutProvider(name == "EEA")

	then
		$eligible.setClassType( "EEAn" );
		update($eligible)
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-eea-eli-n"
	when
	    $asset: Assets(CQS in ( 1, 2, 3 ))
		$eligible: EligibleResult(classType == "EEAn")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end
