package com.acuo.rules.eligibility

import org.slf4j.Logger
import com.acuo.common.model.assets.*
import java.lang.Number

global Logger log;

rule "eea-FXHaircut-im-a"
	when
		$ag: LocalAgreement(marginType == "Initial")
		$asset: LocalAsset(currency!= $ag.terminateCurrency)
		$provider: HaircutProvider(name == "EEA")
		$eligible: Eligible()
	then
		$eligible.setFxHaircut( 0.08 );
		update($eligible);
		System.out.println("fire eea-FXHaircut-im-a");
end

