package com.acuo.rules.eligibility

import org.slf4j.Logger

global Logger log;

rule "rule-fitch-cash-haircut"
	when
		$provider:HaircutProvider(name=="Fitch")
		$agree:LocalAgreement()
		$asset:LocalAsset(currency in $agree.baseCurrency)
		$eligible:Eligible()
	then
	    $eligible.isEligible(true);
		$eligible.setFxHaircut(0);
		$eligible.setHaircut(0);
		update($eligible);
		System.out.println("fire rule-fitch-cash-haircut");
end