package com.acuo.rules.eligibility

import org.slf4j.Logger

global Logger log;

rule "rule-fitch-haircut-cmpt"
agenda-group "FitchHaircut"
	when
		$provider:HaircutProvider(name=="Fitch")
		$eligible:Eligible($secAR: securityAR!=-1, $fxAR: FXAR!=-1)
	then
		$eligible.setFxHaircut(0);
		$eligible.setHaircut(1- $secAR * $fxAR);
		update($eligible);
		System.out.println("fire rule-fitch-haircut-cmpt");
end

