package com.acuo.rules.eligibility

import org.slf4j.Logger

global Logger log;

rule "issuerInMultiDevBank"
	when
		$issuer : Issuer(name in ("Nordic Investment Bank",
                                  "International Bank for Reconstruction and Development",
                                  "INTERNATIONAL FINANCE CORPORATION",
                                  "Inter-American Development Bank",
                                  "Asian Development Bank",
                                  "African Development Bank",
                                  "COUNCIL OF EUROPE DEVELOPMENT BANK",
                                  "Caribbean Development Bank",
                                  "European Bank for Reconstruction and Development",
                                  "European Investment Bank",
                                  "European Investment Fund",
                                  "Multilateral Investment Guarantee Agency",
                                  "INTERNATIONAL FINANCE FACILITY FOR IMMUNISATION COMPANY",
                                  "Islamic Development Bank"));
	then
		$issuer.setIsMultiDevBank( true );
		update($issuer);
        log.info("Rule: '{}'", drools.getRule().getName());
end
