package com.acuo.rules.eligibility

import org.slf4j.Logger

global Logger log;

rule "issuerInSovLess20RW"
	when
		$issuer : Issuer(name in ( "Commonwealth of Australia",
                                  "Republic of Austria",
                                  "Kingdom of Belgium",
                                  "Canada",
                                  "Republic of Chile",
                                  "People's Republic of China[k]",
                                  "Kingdom of Denmark",
                                  "Republic of Estonia",
                                  "Republic of Finland",
                                  "French Republic",
                                  "Federal Republic of Germany",
                                  "State of Israel",
                                  "Japan",
                                  "Ireland",
                                  "State of Kuwait",
                                  "Republic of Latvia",
                                  "Grand Duchy of Luxembourg",
                                  "Malaysia",
                                  "Republic of Malta",
                                  "Kingdom of the Netherlands",
                                  "NewZealand",
                                  "Kingdom of Norway",
                                  "Republic of Poland",
                                  "Kingdom of Saudi Arabia",
                                  "Republic of Singapore",
                                  "Slovak Republic",
                                  "Republic of Slovenia",
                                  "Kingdom of Sweden",
                                  "Swiss Confederation",
                                  "Syrian Arab Republic",
                                  "United Kingdom of Great Britain and Northern Ireland"));
	then
		$issuer.setIsSovRWLess20( true );
		update($issuer);
        log.info("Rule: '{}'", drools.getRule().getName());
end
