package com.acuo.rules.eligibility

import com.acuo.common.model.assets.Assets

import org.slf4j.Logger
global Logger log;

rule "issuerInMemberStates"
	when
		$asset : Assets(issuerCountryCode in ("AT","BE","BG","HR","CY",
                                  "CZ","DK","EE","FI","FR",
                                  "DE","GR","HU","IE","IT",
                                  "LV","LT","LU","MT","NL",
                                  "PL","PT","RO","SK","SI",
                                  "ES","SE","GB"));
	then
		$asset.setIssuerIsMemberState( true );
		update($asset);
        log.info("Rule: '{}'", drools.getRule().getName());
end
