package com.acuo.rules.eligibility

import org.slf4j.Logger

global Logger log;

rule "rule-us-class-10"
	when
		$asset : LocalAsset( type == "gold" )
		$eligible: Eligible()
		$provider: HaircutProvider(name == "US")

	then
	log.info(
                "Rule: '{}', asset: '{}', issuer:'{}'",
                drools.getRule().getName(),
                $asset
            );

		$eligible.setClassType( "US10" );
		update($eligible)
end

rule "rule-us-eli-10"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "US10")
	then
		$eligible.setIsEligible( true );
		update($eligible);
		System.out.println("fire rule-US-eli-10");
end
