package com.acuo.rules.eligibility

import org.slf4j.Logger

global Logger log;

rule "rule-us-class-8b"
	when
		$asset : LocalAsset( type == "equity")
		$provider: HaircutProvider(name == "US",inusMainIndex($asset.index) == 1)
		$eligible: Eligible()


	then

		$eligible.setClassType( "US8b" );
		update($eligible)
end

rule "rule-us-eli-8b"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "US8b")
	then
		$eligible.setIsEligible( true );
		update($eligible);
		System.out.println("fire rule-US-eli-8b");
end
