package com.acuo.rules.eligibility

import org.slf4j.Logger

global Logger log;

function boolean substrInStr(String substr,String str) {
    return str.toLowerCase().contains(substr.toLowerCase());
}

rule "rule-us-class-1"
	when
		$asset : LocalAsset( type == "cash",$currency:currency )
		$agreement: LocalAgreement($majorCurrency:majorCurrency,$settlementCurrency:settlementCurrency)
		$methods: Methods()
		eval($methods.substrInStr($currency,$majorCurrency)||$currency==$settlementCurrency)
		$eligible: Eligible()
		$provider: HaircutProvider(name == "US")

	then
	log.info(
                "Rule: '{}', asset: '{}'",
                drools.getRule().getName(),
                $asset
            );

		$eligible.setClassType( "US1" );
		update($eligible)
end

rule "rule-US-eli-1"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "US1")
	then
		log.info(
                    "Rule: '{}', asset: '{}'",
                    drools.getRule().getName(),
                    $asset
                );
		$eligible.setIsEligible( true );
		update($eligible);
		System.out.println("fire rule-US-eli-1");
end
