package com.acuo.rules.eligibility

import org.slf4j.Logger

global Logger log;

rule "rule-us-class-2"
	when
		$asset : LocalAsset( type == "bond" )
		$issuer : Issuer(name=="UNITED STATES TREASURY")
		$eligible: Eligible()
		$provider: HaircutProvider(name == "US")

	then

		$eligible.setClassType( "US2" );
		update($eligible)
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-us-eli-2"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "US2")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end
