package com.acuo.rules.eligibility

import org.slf4j.Logger

global Logger log;

rule "rule-us-class-6"
	when
		$asset : LocalAsset( type == "bond" )
		$issuer : Issuer(isMultiDevBank)
		$eligible: Eligible()
		$provider: HaircutProvider(name == "US")

	then

		$eligible.setClassType( "US6" );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-us-eli-6"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "US6")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end
