package com.acuo.rules.eligibility

import org.slf4j.Logger

global Logger log;

rule "rule-us-class-8a"
	when
		$asset : LocalAsset( type == "equity")
		$regime: Regime(name == "US",inusMainIndex($asset.index) == 0)
		$eligible: Eligible()


	then

		$eligible.setClassType( "US8a" );
		update($eligible)
end

rule "rule-us-eli-8a"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "US8a")
	then
		$eligible.setIsEligible( true );
		update($eligible)
end
