package com.acuo.rules.eligibility

import org.slf4j.Logger
import java.util.List;
import java.util.ArrayList;
import java.io.*;
import java.util.*;
global Logger log;

function boolean substrInStr(String substr,String str) {
    return str.toLowerCase().contains(substr.toLowerCase());
}

rule "rule-us-class-1"
	when
		$asset : LocalAsset( type == "cash" )
		$agreement: LocalAgreement(substrInStr($asset.currency,majorCurrency) ||$asset.currency==settlementCurrency )
		$eligible: Eligible()
		$regime: Regime(name == "US")

	then
	log.info(
                "Rule: '{}', asset: '{}'",
                drools.getRule().getName(),
                $asset
            );

		$eligible.setClassType( "US1" );
		update($eligible)
end

rule "rule-US-eli-a"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "US1")
	then
		log.info(
                    "Rule: '{}', asset: '{}'",
                    drools.getRule().getName(),
                    $asset
                );
		$eligible.setIsEligible( true );
		update($eligible)
end
