package com.acuo.rules.eligibility

import org.slf4j.Logger

global Logger log;

rule "rule-us-class-6"
	when
		$asset : LocalAsset( type == "bond" )
		$issuer : Issuer(isMultiDevBank)
		$eligible: Eligible()
		$provider: HaircutProvider(name == "US")

	then
	log.info(
                "Rule: '{}', asset: '{}', issuer:'{}'",
                drools.getRule().getName(),
                $asset,
                $issuer
            );

		$eligible.setClassType( "US6" );
		update($eligible)
end

rule "rule-us-eli-6"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "US6")
	then
		$eligible.setIsEligible( true );
		update($eligible);
		System.out.println("fire rule-US-eli-6");
end
