package com.acuo.rules.eligibility

import org.slf4j.Logger

global Logger log;

rule "rule-us-class-4"
	when
		$asset : LocalAsset( type == "bond" )
		$issuer : Issuer(isEUCtrBank||isSovRWLess20)
		$eligible: Eligible()
		$provider: HaircutProvider(name == "US")

	then

		$eligible.setClassType( "US4" );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-us-eli-4"
	when
		$asset : LocalAsset( )
		$eligible: Eligible(classType == "US4")
	then
		log.info(
                    "Rule: '{}', asset: '{}', eligible:'{}'",
                    drools.getRule().getName(),
                    $asset,
                    $eligible
                );
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end
