package com.acuo.rules.eligibility

import com.acuo.common.model.assets.Assets
import com.acuo.common.model.agreements.Agreement
import com.acuo.common.model.margin.Types
import com.opengamma.strata.basics.currency.Currency
import org.slf4j.Logger
global Logger log;

function boolean ccyInCcys(com.opengamma.strata.basics.currency.Currency ccy, com.opengamma.strata.basics.currency.Currency[] ccys){
    Currency current;
    int number = ccys.length;
    for(int i=0;i<number;i++){
        current = ccys[i];
        if(current==ccy){
            return true;
        }
    }
    return false;
}

rule "rule-us-class-1"
	when
		$asset : Assets( type == "cash",$currency:currency )
		$agreement: Agreement($majorCurrency:majorCurrency,$settlementCurrency:settlementCurrency)
		eval(ccyInCcys($currency,$majorCurrency)||$currency==$settlementCurrency)
		//eval($majorCurrency contains $currency||
		//eval(ccyInCcys($currency,$majorCurrency))
		//eval($currency==$settlementCurrency)
		$eligible: EligibleResult()
		$provider: HaircutProvider(name == "US")
	then
		$eligible.setClassType( "US1" );
		update($eligible)
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-US-eli-1"
	when
		$asset : Assets( )
		$eligible: EligibleResult(classType == "US1")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-us-class-2"
	when
		$asset : Assets( assetType == "GOVT" )
		$issuer : Issuer(countryCode=="US")
		$eligible: EligibleResult()
		$provider: HaircutProvider(name == "US")
	then
		$eligible.setClassType( "US2" );
		update($eligible)
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-us-eli-2"
	when
		$asset : Assets( )
		$eligible: EligibleResult(classType == "US2")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-us-class-3"
	when
		$asset : Assets( assetType=="AGNC" )
		$issuer : Issuer(countryCode == "US")
		$eligible: EligibleResult()
		$provider: HaircutProvider(name == "US")
	then
		$eligible.setClassType( "US3" );
		update($eligible)
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-us-eli-3"
	when
		$asset : Assets( )
		$eligible: EligibleResult(classType == "US3")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-us-class-4"
	when
		$asset : Assets( assetType=="GOVT" )
		$issuer : Issuer(isMemberState)
		$eligible: EligibleResult()
		$provider: HaircutProvider(name == "US")
	then
		$eligible.setClassType( "US4" );
		update($eligible);
        log.info("Rule: '{}', asset: '{}',issuer:'{}'", drools.getRule().getName(), $asset, $issuer );
end

rule "rule-us-eli-4"
	when
		$asset : Assets( )
		$eligible: EligibleResult(classType == "US4")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-us-class-6"
	when
		$asset : Assets( )
		$issuer : Issuer(sector=="SPRA")
		$eligible: EligibleResult()
		$provider: HaircutProvider(name == "US")
	then
		$eligible.setClassType( "US6" );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-us-eli-6"
	when
		$asset : Assets( )
		$eligible: EligibleResult(classType == "US6")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-us-class-10"
	when
		$asset : Assets( type == "gold" )
		$eligible: EligibleResult()
		$provider: HaircutProvider(name == "US")
	then
		$eligible.setClassType( "US10" );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "rule-us-eli-10"
	when
		$asset : Assets( )
		$eligible: EligibleResult(classType == "US10")
	then
		$eligible.setIsEligible( true );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end
