package com.acuo.rules.eligibility

import org.slf4j.Logger
import com.acuo.common.model.assets.*
import java.lang.Number

global Logger log;

rule "us-FXHaircut-vm"
	when
		$asset: LocalAsset(type!= "cash")
		$agreement: Agreement(marginType == "Variation", (substrInStr($asset.currency,majorCurrency) ||$asset.currency==settlementCurrency) )
		$regime: Regime(name == "US")
	then
		$asset.setFXHaircut( 0 );
		update($asset)
end

