package com.acuo.rules.eligibility

import com.acuo.common.model.assets.Assets
import com.acuo.common.model.agreements.Agreement
import com.acuo.common.model.margin.Types
import org.slf4j.Logger
global Logger log;

rule "us-FXHaircut-im"
	when
		$ag: Agreement(marginType == Types.MarginType.Initial)
		$asset: Assets(currency== $ag.getTerminateCurrency() || currency == $ag.getSettlementCurrency())
		$provider: HaircutProvider(name == "US")
		$eligible: EligibleResult()
	then
		$eligible.setFxHaircut( 0 );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "us-FXHaircut-im-a"
	when
		$ag: Agreement(marginType == Types.MarginType.Initial)
		$asset: Assets(currency!= $ag.getTerminateCurrency() && currency != $ag.getSettlementCurrency())
		$provider: HaircutProvider(name == "US")
		$eligible: EligibleResult()
	then
		$eligible.setFxHaircut( 0.08 );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "us-FXHaircut-vm"
	when
		$asset: Assets(type!= "cash",$currency:currency)
		$agreement: Agreement(marginType == Types.MarginType.Variation,$majorCurrency:majorCurrency,$settlementCurrency:settlementCurrency)
		eval(ccyInCcys($currency,$majorCurrency)||$currency==$settlementCurrency)
		$provider: HaircutProvider(name == "US")
		$eligible: EligibleResult()
	then
		$eligible.setFxHaircut( 0 );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end

rule "us-FXHaircut-vm-a"
	when
		$asset: Assets(type!= "cash",$currency:currency)
		$agreement: Agreement(marginType == Types.MarginType.Variation,$majorCurrency:majorCurrency,$settlementCurrency:settlementCurrency)
		eval(!(ccyInCcys($currency,$majorCurrency)||$currency==$settlementCurrency))
		$provider: HaircutProvider(name == "US")
		$eligible: EligibleResult()
	then
		$eligible.setFxHaircut( 0.08 );
		update($eligible);
        log.info("Rule: '{}', asset: '{}'", drools.getRule().getName(), $asset );
end


