package com.acuo.rules.eligibility

import org.slf4j.Logger
import java.lang.Number

global Logger log;

rule "us-FXHaircut-vm-a"
	when
		$asset: LocalAsset(type!= "cash")
		$agreement: LocalAgreement(marginType == "Variation", !(substrInStr($asset.currency,majorCurrency) ||$asset.currency==settlementCurrency) )
		$regime: Regime(name == "US")
		$eligible: Eligible()
	then
		$eligible.setFxHaircut( 0.08 );
		update($eligible)
end

