package com.acuo.rules.eligibility

import org.slf4j.Logger
import com.acuo.common.model.assets.*

import java.util.List;
import java.util.ArrayList;
import java.io.*;
import java.util.*;

global Logger log;

function int inusMainIndex(String index)
{
    String e[]=index.split(",");
    String bench[]={"S&P 500",
                    "S&P 1500"};
    int flag = 0;
    int type = 2;
    for(int i = 0; i < e.length; i++)
    {
    System.out.println("e:" + e[i]);
        for(int j = 0; j < bench.length; j++)
        {
         System.out.println("bench"+j+":" + bench[j] +"  " + "e"+i +":"+ e[i]+ "   " + "Judge:"+(bench[j].equals(e[i])));
	     if (bench[j].equals(e[i]))
         {
		  flag = 1;
		  type = j;
		  break;
         }
        }
        if (flag==1 && type==0)
         {
              break;

         }
    }

    if (flag==1)
        {
            return type;

        }
    else
        {
            return 2;
        }

}

