package com.acuo.rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Client implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String id;
   private java.lang.String entityLei;

   private java.lang.String name;

   private java.lang.String ultimateParentLei;

   private java.lang.String ultimateParentName;

   public Client()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getEntityLei()
   {
      return this.entityLei;
   }

   public void setEntityLei(java.lang.String entityLei)
   {
      this.entityLei = entityLei;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getUltimateParentLei()
   {
      return this.ultimateParentLei;
   }

   public void setUltimateParentLei(java.lang.String ultimateParentLei)
   {
      this.ultimateParentLei = ultimateParentLei;
   }

   public java.lang.String getUltimateParentName()
   {
      return this.ultimateParentName;
   }

   public void setUltimateParentName(java.lang.String ultimateParentName)
   {
      this.ultimateParentName = ultimateParentName;
   }

   public Client(java.lang.String id, java.lang.String entityLei,
         java.lang.String name, java.lang.String ultimateParentLei,
         java.lang.String ultimateParentName)
   {
      this.id = id;
      this.entityLei = entityLei;
      this.name = name;
      this.ultimateParentLei = ultimateParentLei;
      this.ultimateParentName = ultimateParentName;
   }

}